name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Build jekyll-scholar-extras
      run: |
        cd jekyll-scholar-extras/
        gem build jekyll-scholar-extras.gemspec
        cd ..

      # Google Scholar seems to be blocking Github runners, so this might fail
    - name: Update citation count
      continue-on-error: true
      run: |
        pip install -r citations/requirements.txt
        python citations/generateScholarCitations.py

    - name: Build Jekyll site
      run: |
        set -xo pipefail
        rm -rf _site/*
        gem install bundler
        bundle install
        bundle exec jekyll build
        cp CNAME _site/CNAME

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: _site # The folder the action should deploy.
