name: Update citations

on:
  # Allow building on-demand
  workflow_dispatch:
  # Rebuild the citations at 12am everyday
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: master
        path: main

    - name: Checkout site
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Update citation count
      run: |
        pip install -r main/citations/requirements.txt
        python main/citations/generateScholarCitations.py main/content/bibliographies/Papers.bib gh-pages/content

    - name: Deploy site update
      if: ${{ success() }}
      env:
        COMMIT_MESSAGE: Update citation count
        COMMIT_AUTHOR: Github Actions
      run: |
        cd gh-pages
        # Only run this part of the workflow if there have been changes in the citation count
        # git diff returns 0 when there are no differences, 1 if there are differences
        git diff --exit-code && exit 0
        git config --global user.name "Ian McInerney"
        git config --global user.email "imciner2@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
